import os 
 
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\sql\ods.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\api_jd_cwxz_increment.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\sql\dwd.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\erp_jd_dwd.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\erp_jd_dws.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\erp_jd_dws\erp_jd_dws_warehouse_ck_dayend.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\sql\dws.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\erp_jd_ads\key_product_doi_fc.py") 
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\sql\ads.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\sql\day.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\erp_jd_dws_qd_dlzy.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\erp_jd_dws\dlzy_inventory_ck_doi.py")
os.system(r"python C:\Users\liujin02\Desktop\BI建设\API_BI\clean\erp_jd_ads\erp_jd_ads_ageofreceivables_1122_06.py")
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\产品首批采购消耗完成时间.py")   
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\核心桌游_扩展滞销风险.py") 
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\渠道客户拿货预警.py") 
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\西西弗代理加单.py") 
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\孩子王代理加单.py") 
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\西西弗自研加单.py") 
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\孩子王自研加单.py") 
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\渠道活动返利计算.py")  
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\毛利比对.py")  
# os.system(r"python C:\Users\liujin02\Desktop\邮件报表\caigou.py") 
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\product_xxf.py")
os.system(r"python C:\Users\liujin02\Desktop\邮件报表\wlgzs.py")